### ISSUE TITLE
Apply coporate design in Documentation theme

### ISSUE THREAD

**Issue by mhoellmann** [agri-gaia/seerep#132]
Adjust the themes of MkDocs and Doxygen to use the colors of the corporate design

see page 6: https://intranet.dfki.de/services/know_how_pool/236/getUpload

**Comment by jarkenau** [comment]
Is there a logo which I could use instead of the defaults? DFKI or Argi-Gaia?

**Comment by mhoellmann** [comment]
We can start with the DFKI Logo, but we should also design a Seerep Logo
