### ISSUE TITLE
Store intrinsics of camera

### ISSUE THREAD

**Issue by Mark-Niemeyer** [agri-gaia/seerep#148]
- [x] add a new data type for the storage of [sensor_msgs](http://docs.ros.org/en/noetic/api/sensor_msgs/html/index-msg.html)/[CameraInfo](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/CameraInfo.html) Message
- [x] define fb message
- [x] define fb gRPC services
- [x] hdf5-io for the new data type (starting with fb). Do most of the io using core-io
- [x] extend the seerep-core. No indexing needed. Only the storage and the loading of a cameraInfo using a UUID is necessary.

Next steps:
- [x] add a field in the image data type to reference the camera info
- [x] only allow the storing of images if an existing cameraInfo is referenced
- [ ] extend hdf5-ros to store CameraInfo
- [x] add pb support

**Comment by 104H** [comment]
PR #293 build the ros-hdf5 support thus concluding this issue.
