### ISSUE TITLE
Image and point cloud attributes defined in two places

### ISSUE THREAD

**Issue by jarkenau** [agri-gaia/seerep#183]
One in the core:

https://github.com/agri-gaia/seerep/blob/8d9cce7abd2a58a6352bd50ba7fde8191c8a0e8b/seerep-hdf5/seerep-hdf5-core/include/seerep-hdf5-core/hdf5-core-image.h#L38-L53

and once in the hdf5 access: 

https://github.com/agri-gaia/seerep/blob/8d9cce7abd2a58a6352bd50ba7fde8191c8a0e8b/seerep-hdf5/seerep-hdf5-fb/include/seerep-hdf5-fb/hdf5-fb-image.h#L43-L55

To-Do: unify into one place.

**Comment by jarkenau** [comment]
@mhoellmann to which place should the definitions be moved? In the Core we have the benefit of using the definitions between fb and pb. But if we have fields which are only supported in one format, it could get confusing.

**Comment by mhoellmann** [comment]
The definitions in the core should be used. The [hdf5-pb-image](https://github.com/agri-gaia/seerep/blob/8d9cce7abd2a58a6352bd50ba7fde8191c8a0e8b/seerep-hdf5/seerep-hdf5-pb/include/seerep-hdf5-pb/hdf5-pb-image.h) already uses the core definitions. It should be done similarly.

**Comment by jarkenau** [comment]
It's now changed for point clouds, should also be done for images and points in fb
