### ISSUE TITLE
hdf5-core-datatype interface unsuitable?

### ISSUE THREAD

**Issue by jarkenau** [agri-gaia/seerep#192]
The `Hdf5CoreDatatypeInterface` provides an interface for all hdf5 access classes, which is used in the core dataset: 

https://github.com/agri-gaia/seerep/blob/aaddf9c7a9b5000fe145dbe5adde7d83b633ca4f/seerep-srv/seerep-core/include/seerep-core/core-dataset.h#L42

But the interface seems out of date, I couldn't  find  a place where the `readDataset(...)` methods are used. 

https://github.com/agri-gaia/seerep/blob/aaddf9c7a9b5000fe145dbe5adde7d83b633ca4f/seerep-hdf5/seerep-hdf5-core/include/seerep-hdf5-core/hdf5-core-datatype-interface.h#L13-L20

We cloud add general `read(...)` and `write (...)` functions to the interface. What do you think about that @mhoellmann?

**Comment by mhoellmann** [comment]
The Hdf5CoreDatatypeInterface  class is a pure virtual class, which only defines the base interface for all the different dataset type classes which must implement the functions. If the do not implement the pure virtual functions, it is not possible to create objects based on the classes. So examples for the read functions:

https://github.com/agri-gaia/seerep/blob/aaddf9c7a9b5000fe145dbe5adde7d83b633ca4f/seerep-hdf5/seerep-hdf5-core/include/seerep-hdf5-core/hdf5-core-image.h#L32-L33
https://github.com/agri-gaia/seerep/blob/aaddf9c7a9b5000fe145dbe5adde7d83b633ca4f/seerep-hdf5/seerep-hdf5-core/include/seerep-hdf5-core/hdf5-core-point-cloud.h#L32-L33

In [seerep/seerep-srv/seerep-core/include/seerep-core/core-dataset.h](https://github.com/agri-gaia/seerep/blob/aaddf9c7a9b5000fe145dbe5adde7d83b633ca4f/seerep-srv/seerep-core/include/seerep-core/core-dataset.h#L42) the seerep_hdf5_core::Hdf5CoreDatatypeInterface is just used as a common parent class of all the data type classes. Thus, all child classes can be assigned to the `hdf5io` and when using `hdf5io` the interface functions defined in Hdf5CoreDatatypeInterface  can be used independent of the actual data type.
