### ISSUE TITLE
Add frame to project info query

### ISSUE THREAD

**Issue by Mark-Niemeyer** [agri-gaia/seerep#196]
Also return the base frame when querying for the project infos

**Comment by 104H** [comment]
Also add geodetic coordinates to the project info query.

**Comment by mhoellmann** [comment]
The frame id is already in the project info: 
https://github.com/agri-gaia/seerep/blob/be36af3b67cac71a376bcf7e379f73fcab9ef0e5/seerep-srv/seerep-server/src/fb-meta-operations.cpp#L49

just extent the fb definition and add it here:
https://github.com/agri-gaia/seerep/blob/be36af3b67cac71a376bcf7e379f73fcab9ef0e5/seerep-srv/seerep-server/src/fb-meta-operations.cpp#L67
