### ISSUE TITLE
Check for tf2 compatible frame_ids

### ISSUE THREAD

**Issue by jarkenau** [agri-gaia/seerep#321]
After the migration from `tf` to `tf2` frame_ids are not allowed to change a leading `/` http://wiki.ros.org/tf2/Migration. We need to check for this requirement in SEEREP before tf2 lib components are used.

**Comment by Mark-Niemeyer** [comment]
We already replaced the `/` by `_` when storing it in hdf5 (see #303). We can use the same approach for this.
