### ISSUE TITLE
Test protobuf write and load of images

### ISSUE THREAD

**Issue by jarkenau** [agri-gaia/seerep#75]
Basically same as #71, but using the [Protocol Buffers](https://developers.google.com/protocol-buffers) specific functions:

https://github.com/agri-gaia/seerep/blob/8295338243fd2b661d348e8e74b305bd557ce0b9/seerep-hdf5/seerep-hdf5-pb/include/seerep-hdf5-pb/hdf5-pb-image.h#L26

https://github.com/agri-gaia/seerep/blob/8295338243fd2b661d348e8e74b305bd557ce0b9/seerep-hdf5/seerep-hdf5-pb/include/seerep-hdf5-pb/hdf5-pb-image.h#L28

**Comment by 104H** [comment]
Tests fail. Problem is defined in #184

**Comment by mhoellmann** [comment]
closed by #170
