### ISSUE TITLE
Test ROS conversions to Flabuffer

### ISSUE THREAD

**Issue by jarkenau** [agri-gaia/seerep#82]
Test if the conversions from ROS-msgs to flatbuffer resp. protobuf works correctly. 

Steps:

1. Pre-Define ROS message
2. Call function to convert ROS message into flatbuffer message
3. Call function to convert flatbuffer message back to ROS message
4. Check if the converted ROS message equals the pre-defined ROS message

**Comment by 104H** [comment]
Closed in PR #186
