### ISSUE TITLE
Add Geolocation during project creation

### ISSUE THREAD

**Issue by mklpiening** [agri-gaia/seerep#96]
Assign a Geodetic position to the root frame of a project. All frames of the project are then in a local cartesian coordinate system with x pointing north and z being the local normal of the ellipsoid

**Comment by mhoellmann** [comment]
duplicate of #34?

**Comment by 104H** [comment]
Steps:
1. Implement new message type of geodetic position
2. Use this as a submessage in the project creation service here [here](https://github.com/agri-gaia/seerep/blob/main/seerep-com/fbs/meta_operations.fbs)
3. Implement logic in the header file [here](https://github.com/agri-gaia/seerep/blob/main/seerep-srv/seerep-server/include/seerep-server/fb-meta-operations.h)
4. Implement logic in cpp file [here](https://github.com/agri-gaia/seerep/blob/main/seerep-srv/seerep-server/src/fb-meta-operations.cpp)
